"""empty message

Revision ID: 74b7d403c717
Revises: 0a593a99d4f7
Create Date: 2020-06-27 13:22:12.802581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74b7d403c717'
down_revision = '0a593a99d4f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'skill', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skill', type_='foreignkey')
    op.drop_column('skill', 'user_id')
    # ### end Alembic commands ###
