"""empty message

Revision ID: c2b3aa2ca3c9
Revises: 8c30115b3611
Create Date: 2020-06-19 14:15:04.425257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2b3aa2ca3c9'
down_revision = '8c30115b3611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class', sa.Column('color_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_class_joinCode'), 'class', ['joinCode'], unique=True)
    op.create_unique_constraint(None, 'student', ['email'])
    op.drop_index('ix_teacher_slug', table_name='teacher')
    op.create_index(op.f('ix_teacher_slug'), 'teacher', ['slug'], unique=False)
    op.create_unique_constraint(None, 'teacher', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher', type_='unique')
    op.drop_index(op.f('ix_teacher_slug'), table_name='teacher')
    op.create_index('ix_teacher_slug', 'teacher', ['slug'], unique=True)
    op.drop_constraint(None, 'student', type_='unique')
    op.drop_index(op.f('ix_class_joinCode'), table_name='class')
    op.drop_column('class', 'color_name')
    # ### end Alembic commands ###
